name: dbt_run_streamline_chainhead
run-name: dbt_run_streamline_chainhead

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Chainhead Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m "fsc_evm,tag:chainhead" "fsc_evm,tag:streamline,tag:core,tag:complete" "fsc_evm,tag:streamline,tag:core,tag:realtime" --exclude "fsc_evm,tag:receipts_by_hash"
      command_name_2: Run Chainhead Tests
      command_2: |
        dbt test -m "fsc_evm,tag:chainhead"
    secrets: inherit